import type { ReactNode } from "react";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import RecoilFrame from "@/components/RecoilFrame";

import type { Metadata } from "next";

import "./globals.css";
import "./font/font.css";

export const metadata: Metadata = {
  title: "아키플 스튜디오",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <RecoilFrame>
          <Header />
          {children}
          <Footer />
        </RecoilFrame>
      </body>
    </html>
  );
}
