import type { ReactNode } from "react";

// eslint-disable-next-line import/order
import type { Metadata } from "next";

import "./globals.css";
import "./font/font.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "아키플 스튜디오",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
