import type { ReactNode } from "react";

import { getServerSession } from "next-auth";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import RecoilFrame from "@/components/RecoilFrame";
import SessionProvider from "@/components/SessionProvider";

import type { Metadata } from "next";
import "./font/font.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "아키플 스튜디오",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession();
  return (
    <html>
      <body>
        <SessionProvider session={session}>
          <RecoilFrame>
            <Header />
            {children}
            <Footer />
          </RecoilFrame>
        </SessionProvider>
      </body>
    </html>
  );
}
